use_cases = [
    "Summarize a long article or document",
    "Rewrite a passage to make it more concise",
    "Simplify technical language for a non-expert audience",
    "Remove unnecessary details from a text",
    "Improve the readability of a dense passage",
    "Clarify a confusing sentence or paragraph",
    "Eliminate repetition in a text",
    "Remove biased or offensive language from a text",
    "Change the tone or voice of a text",
    "Translate a text into simpler language or a different language altogether",
    "Reformulate a sentence to make it more engaging or interesting",
    "Change the point of view of a text",
    "Add additional information or detail to a text",
    "Adjust the pacing of a story or narrative",
    "Remove jargon or technical terms from a text",
    "Adjust the level of formality in a text",
    "Simplify complex instructions or directions",
    "Improve the clarity of a legal document or contract",
    "Rewrite a marketing message to be more persuasive",
    "Adapt a story or script for a different audience or medium",
    "Adjust the length of a text to fit a specific requirement",
    "Remove unnecessary or irrelevant examples from a text",
    "Correct grammar or spelling errors in a text",
    "Add additional context or explanation to a text",
    "Reframe a controversial statement to be less offensive or more inclusive",
    "Rewrite a product description to be more compelling or informative",
    "Remove redundant or repetitive phrases from a text",
    "Adjust the sentence structure of a text to improve flow and readability",
    "Clarify technical jargon in a scientific paper or research article",
    "Improve the accuracy of a historical or scientific account",
    "Simplify complex financial data for a non-expert audience",
    "Adjust the tone of a message to be more polite or formal",
    "Remove vague or unclear language from a text",
    "Reframe a negative review or comment to be more constructive",
    "Improve the clarity and readability of a complex data visualization or chart",
    "Simplify a complex math problem or equation for a non-expert audience",
    "Clarify ambiguous instructions in a technical manual or guide",
    "Remove unnecessary technical detail from a software specification or documentation",
    "Improve the clarity and flow of a legal argument",
    "Reformulate a scientific hypothesis to be more precise or testable",
    "Simplify the instructions for assembling or operating a device or machine",
    "Improve the clarity and accuracy of a news article or report",
    "Adjust the tone or voice of a character in a novel or screenplay",
    "Simplify a complex recipe or cooking instructions",
    "Remove unnecessary background information from a text",
    "Improve the clarity and accuracy of a user interface or user experience design",
    "Adjust the level of detail in a technical report or white paper",
    "Simplify complex medical terminology for a patient or non-expert audience",
    "Clarify complex legal terminology for a non-lawyer audience",
    "Adapt a scientific theory or concept for a popular audience or layperson",
    "Revise a blog post to be more engaging and informative",
    "Correct the formatting of a text document",
    "Add citations or references to a research paper",
    "Make a text more visually appealing with images or graphics",
    "Condense a series of emails into a single message",
    "Create a table or chart to summarize data in a report",
    "Simplify a technical diagram for a non-technical audience",
    "Add humor or wit to a piece of text"

]

tones = [
    'Abstruse',
    'Amiable',
    'Apologetic',
    'Appreciative',
    'Authoritative',
    'Benevolent',
    'Blunt',
    'Candid',
    'Cantankerous',
    'Caustic',
    'Cerebral',
    'Cheerful',
    'Chummy',
    'Circuitous',
    'Clinical',
    'Colloquial',
    'Compassionate',
    'Conciliatory',
    'Confessional',
    'Confrontational',
    'Contemplative',
    'Contemptuous',
    'Conversational',
    'Critical',
    'Cryptic',
    'Cynical',
    'Defensive',
    'Depressed',
    'Despondent',
    'Detached',
    'Didactic',
    'Diffident',
    'Direct',
    'Disparaging',
    'Dramatic',
    'Dreamy',
    'Dry',
    'Earnest',
    'Evasive',
    'Excitable',
    'Factual',
    'Fanciful',
    'Fatalistic',
    'Fawning',
    'Fierce',
    'Flippant',
    'Forceful',
    'Formal',
    'Friendly',
    'Frustrated',
    'Furtive',
    'Gentle',
    'Gloomy',
    'Graceful',
    'Gracious',
    'Grandiose',
    'Grim',
    'Grouchy',
    'Guarded',
    'Hard',
    'Harsh',
    'Haughty',
    'Hesitant',
    'Hopeful',
    'Hostile',
    'Humorous',
    'Hypercritical',
    'Hypnotic',
    'Impartial',
    'Impassioned',
    'Imperious',
    'Imploring',
    'Impressionistic',
    'Incredulous',
    'Indifferent',
    'Indignant',
    'Informal',
    'Inquisitive',
    'Insistent',
    'Intense',
    'Intimate',
    'Intrusive',
    'Ironic',
    'Irreverent',
    'Jaded',
    'Jovial',
    'Judgmental',
    'Laudatory',
    'Lecturing',
    'Lyrical',
    'Matter-of-fact',
    'Melancholic',
    'Militant',
    'Mocking',
    'Moralistic',
    'Mysterious',
    'Neutral',
    'Nihilistic',
    'Nostalgic',
    'Objective',
    'Oblique',
    'Obnoxious',
    'Obscure',
    'Optimistic',
    'Pessimistic',
    'Philosophical',
    'Pithy',
    'Playful',
    'Poignant',
    'Pompous',
    'Practical',
    'Preachy',
    'Pretentious',
    'Provocative',
    'Questioning',
    'Quizzical',
    'Realistic',
    'Reflective',
    'Regretful',
    'Resigned',
    'Respectful',
    'Restrained',
    'Reverent',
    'Romantic',
    'Sarcastic',
    'Satirical',
    'Scathing',
    'Sensual',
    'Sentimental',
    'Serious',
    'Severe',
    'Sharp',
    'Skeptical',
    'Solemn',
    'Som',
    'Somber',
    'Sophisticated',
    'Soulful',
    'Speculative',
    'Spiritual',
    'Stoic',
    'Studious',
    'Subjective',
    'Submissive',
    'Subtle',
    'Sulky',
    'Sullen',
    'Superficial',
    'Superior',
    'Supportive',
    'Surprised',
    'Suspenseful',
    'Suspicious',
    'Sympathetic',
    'Taunting',
    'Tentative',
    'Thoughtful',
    'Threatening',
    'Tongue-in-cheek',
    'Tough',
    'Tragic',
    'Tranquil',
    'Turgid',
    'Unassuming',
    'Unbiased',
    'Uncertain',
    'Unctuous',
    'Understanding',
    'Unforgiving',
    'Uninvolved',
    'Unsympathetic',
    'Uplifting',
    'Urgent',
    'Vacuous',
    'Vague',
    'Vexed',
    'Vibrant',
    'Vicious',
    'Vindictive',
    'Violent',
    'Vivacious',
    'Wary',
    'Whimsical',
    'Wistful',
    'Witty',
    'World-weary',
    'Worried',
    'Wry',
    'Zealous',
    'Zesty',
    'Zippy'
]
