tones = [
    'Abstruse',
    'Amiable',
    'Apologetic',
    'Appreciative',
    'Authoritative',
    'Benevolent',
    'Blunt',
    'Candid',
    'Cantankerous',
    'Caustic',
    'Cerebral',
    'Cheerful',
    'Chummy',
    'Circuitous',
    'Clinical',
    'Colloquial',
    'Compassionate',
    'Conciliatory',
    'Confessional',
    'Confrontational',
    'Contemplative',
    'Contemptuous',
    'Conversational',
    'Critical',
    'Cryptic',
    'Cynical',
    'Defensive',
    'Depressed',
    'Despondent',
    'Detached',
    'Didactic',
    'Diffident',
    'Direct',
    'Disparaging',
    'Dramatic',
    'Dreamy',
    'Dry',
    'Earnest',
    'Evasive',
    'Excitable',
    'Factual',
    'Fanciful',
    'Fatalistic',
    'Fawning',
    'Fierce',
    'Flippant',
    'Forceful',
    'Formal',
    'Friendly',
    'Frustrated',
    'Furtive',
    'Gentle',
    'Gloomy',
    'Graceful',
    'Gracious',
    'Grandiose',
    'Grim',
    'Grouchy',
    'Guarded',
    'Hard',
    'Harsh',
    'Haughty',
    'Hesitant',
    'Hopeful',
    'Hostile',
    'Humorous',
    'Hypercritical',
    'Hypnotic',
    'Impartial',
    'Impassioned',
    'Imperious',
    'Imploring',
    'Impressionistic',
    'Incredulous',
    'Indifferent',
    'Indignant',
    'Informal',
    'Inquisitive',
    'Insistent',
    'Intense',
    'Intimate',
    'Intrusive',
    'Ironic',
    'Irreverent',
    'Jaded',
    'Jovial',
    'Judgmental',
    'Laudatory',
    'Lecturing',
    'Lyrical',
    'Matter-of-fact',
    'Melancholic',
    'Militant',
    'Mocking',
    'Moralistic',
    'Mysterious',
    'Neutral',
    'Nihilistic',
    'Nostalgic',
    'Objective',
    'Oblique',
    'Obnoxious',
    'Obscure',
    'Optimistic',
    'Pessimistic',
    'Philosophical',
    'Pithy',
    'Playful',
    'Poignant',
    'Pompous',
    'Practical',
    'Preachy',
    'Pretentious',
    'Provocative',
    'Questioning',
    'Quizzical',
    'Realistic',
    'Reflective',
    'Regretful',
    'Resigned',
    'Respectful',
    'Restrained',
    'Reverent',
    'Romantic',
    'Sarcastic',
    'Satirical',
    'Scathing',
    'Sensual',
    'Sentimental',
    'Serious',
    'Severe',
    'Sharp',
    'Skeptical',
    'Solemn',
    'Som',
    'Somber',
    'Sophisticated',
    'Soulful',
    'Speculative',
    'Spiritual',
    'Stoic',
    'Studious',
    'Subjective',
    'Submissive',
    'Subtle',
    'Sulky',
    'Sullen',
    'Superficial',
    'Superior',
    'Supportive',
    'Surprised',
    'Suspenseful',
    'Suspicious',
    'Sympathetic',
    'Taunting',
    'Tentative',
    'Thoughtful',
    'Threatening',
    'Tongue-in-cheek',
    'Tough',
    'Tragic',
    'Tranquil',
    'Turgid',
    'Unassuming',
    'Unbiased',
    'Uncertain',
    'Unctuous',
    'Understanding',
    'Unforgiving',
    'Uninvolved',
    'Unsympathetic',
    'Uplifting',
    'Urgent',
    'Vacuous',
    'Vague',
    'Vexed',
    'Vibrant',
    'Vicious',
    'Vindictive',
    'Violent',
    'Vivacious',
    'Wary',
    'Whimsical',
    'Wistful',
    'Witty',
    'World-weary',
    'Worried',
    'Wry',
    'Zealous',
    'Zesty',
    'Zippy'
]



instruction_prompt = ['Cooking - Write a recipe for a classic spaghetti carbonara.',
'Fitness - Create a 30-day workout plan for someone looking to improve their upper body strength.',
'Gardening - Give step-by-step instructions for planting and caring for a tomato plant.',
'DIY - Describe how to build a simple bookshelf using only hand tools.',
'Beauty - Provide a guide for a beginner's skincare routine.',
'Programming - Write out the steps to create a basic calculator using Python.',
'Crafting - Explain how to make a paper flower bouquet for a wedding.',
'Home improvement - Give instructions for installing a ceiling fan.',
'Music - Write a tutorial on how to play the basic chords on a guitar.',
'Painting - Provide a step-by-step guide on painting a landscape using acrylics.',
'Baking - Describe how to make a sourdough starter from scratch.',
'Photography - Write a guide for taking better portraits using natural light.',
'Sewing - Explain how to sew a basic tote bag.',
'Drawing - Provide step-by-step instructions for drawing a realistic eye.',
'Writing - Write out the steps for developing a plot for a novel.',
'Knitting - Give instructions for knitting a simple scarf.',
'Yoga - Provide a guide for practicing the sun salutation sequence.',
'Meditation - Explain how to meditate for beginners.',
'Pet care - Give instructions for grooming a dog.',
'Car maintenance - Provide a step-by-step guide for changing a flat tire.',
'House cleaning - Write out a cleaning checklist for a spring cleaning session.',
'Cocktail making - Give instructions for making a classic mojito.',
'Cake decorating - Describe how to create a buttercream rosette cake.',
'Foreign language - Provide a guide for learning basic phrases in French.',
'Woodworking - Write out the steps for building a simple birdhouse.',
'Jewelry making - Explain how to make a beaded necklace.',
'Running - Provide a guide for training for a 5k race.',
'Childcare - Give instructions for making a simple homemade play dough.',
'Makeup - Write a tutorial for a natural everyday makeup look.',
'Pottery - Explain how to create a pinch pot from clay.',
'Fishing - Provide a guide for tying basic fishing knots.',
'Rock climbing - Write out the steps for tying a figure-eight knot.',
'Skateboarding - Give instructions for performing an ollie.',
'Surfing - Provide a guide for paddling out to catch a wave.',
'Painting furniture - Describe how to paint a dresser with chalk paint.',
'Calligraphy - Provide step-by-step instructions for writing a basic calligraphy alphabet.',
'Soap making - Explain how to make a basic cold process soap.',
'Wine tasting - Write a guide for tasting and evaluating different types of wine.',
'Horseback riding - Provide a guide for mounting a horse.',
'Dancing - Give instructions for learning the basic steps of salsa dancing.',
'Fishing - Write a guide for fishing for trout in a river.',
'Sewing - Provide a guide for reading and using a sewing pattern.',
'Skateboarding - Explain how to perform a kickflip.',
'Makeup - Write out the steps for creating a dramatic smokey eye.',
'Pottery - Provide a guide for throwing a basic bowl on a pottery wheel.',
'Hair styling - Give instructions for creating beachy waves with a curling iron.',
'Writing - Write a guide for writing a persuasive essay.',
'Painting - Explain how to create a textured abstract painting using acrylics.
'Music - Give instructions for playing a basic drum beat on a drum'
]
