# BUILDER #
############

# pull official base image
FROM python:3.9.6-slim-buster as builder

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Upgrade pip
RUN pip install --upgrade pip

# Install dependencies
COPY ./requirements.txt .
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    libssl-dev \
    python3-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
        build-essential \
        libffi-dev \
        libssl-dev \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*

# FINAL #
#########

# pull official base image
FROM python:3.9.6-slim-buster

# create directory for the app
WORKDIR /home/app

# install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# copy entrypoint.dev.sh
COPY ./entrypoint.dev.sh .
RUN sed -i 's/\r$//g' entrypoint.dev.sh
RUN chmod +x entrypoint.dev.sh

# copy project
COPY . .

# run entrypoint.dev.sh
ENTRYPOINT ["./entrypoint.dev.sh"]
