version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    # volumes:
    #   - mysql_data:/var/lib/mysql/data/
    env_file:
    - /code/app/.env.dev
    environment:
    - MYSQL_DATABASE=nexia
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=Pegasus@2010
    - MYSQL_ROOT_PASSWORD=Pegasus@2010
    ports:
    - "3306:3306"

  web:
    build:
      context: .
      dockerfile: docker/dev/python/Dockerfile.dev
    # volumes:
    # - ../../../../app:/app
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - /code/app/.env.dev
    depends_on:
      - db
      # - redis

  # nginx:
  #   build: ./nginx
  #   # volumes:
  #   #   - static_volume:/home/app/web/staticfiles
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

  # celery:
  #   build:
  #     context: ../../
  #     dockerfile: docker/dev/python/Dockerfile.dev
  #   command: celery --app=core worker --loglevel=info --logfile=logs/celery.log
  #   # volumes:
  #     # - ../../../../app:/app
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - web
  #     - redis

  # redis:
  #   image: redis:7-alpine

  # task_dashboard:
  #   build:
  #     context: ../../
  #     dockerfile: docker/dev/python/Dockerfile.dev
  #   command: celery flower -A core --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - 5555:5555
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - web
  #     - redis
  #     - celery

# volumes:
#   mysql_data:
#  static_volume:
