# Generated by Django 4.0 on 2023-10-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProviderAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, verbose_name='API Provider')),
                ('api_key', models.CharField(max_length=100, verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'LLM Provider API',
                'verbose_name_plural': 'LLM Provider APIs',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(verbose_name='Prompt Template')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
        migrations.CreateModel(
            name='OpenAIChatQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.modelproviderapi')),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='llm.prompt')),
            ],
        ),
    ]
