# Generated by Django 3.2.18 on 2023-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=True),
        ),
    ]
