# Generated by Django 3.2.18 on 2023-04-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(blank=True, choices=[('BASIC', 'BASIC'), ('PRO', 'PRO'), ('ULTRA', 'ULTRA'), ('MEGA', 'MEGA'), ('CUSTOM', 'CUSTOM'), ('PENDING', 'PENDING')], max_length=50, null=True),
        ),
    ]
