# Generated by Django 3.2.18 on 2023-04-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_app_user',
            field=models.BooleanField(default=False),
        ),
    ]
