# Generated by Django 3.2.18 on 2023-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pricingplan_monthly_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='additional_character_charge',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro'), ('ultra', 'Ultra'), ('mega', 'Mega'), ('custom', 'Custom')], max_length=50, null=True),
        ),
    ]
