# Generated by Django 3.2.18 on 2023-04-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230420_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='name',
        ),
        migrations.AddField(
            model_name='usecase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promptcategory'),
        ),
    ]
