# Generated by Django 3.2.18 on 2023-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230424_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='monthly_audio_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='monthly_image_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='monthly_video_limit',
            field=models.IntegerField(default=0),
        ),
    ]
