# Generated by Django 3.2.18 on 2023-04-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230427_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='nov',
        ),
        migrations.DeleteModel(
            name='InstructionCategory',
        ),
    ]
