# Generated by Django 3.2.18 on 2023-04-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230424_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='total_audios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='total_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='total_videos',
            field=models.IntegerField(default=0),
        ),
    ]
