# Generated by Django 3.2.18 on 2023-04-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230420_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('anger_score', models.FloatField(blank=True, null=True)),
                ('disgust_score', models.FloatField(blank=True, null=True)),
                ('fear_score', models.FloatField(blank=True, null=True)),
                ('joy_score', models.FloatField(blank=True, null=True)),
                ('neutral_score', models.FloatField(blank=True, null=True)),
                ('sadness_score', models.FloatField(blank=True, null=True)),
                ('surprise_score', models.FloatField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('positive', models.FloatField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='usecase',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tokenusage',
            name='model',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='storage_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='PromptCategory',
        ),
        migrations.DeleteModel(
            name='Tone',
        ),
        migrations.DeleteModel(
            name='UseCase',
        ),
    ]
