# Generated by Django 3.2.18 on 2023-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='duration',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
