# Generated by Django 3.2.18 on 2023-04-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230424_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='data_storage_limit',
            new_name='monthly_data_storage_limit',
        ),
        migrations.RenameField(
            model_name='pricingplan',
            old_name='rate_limit',
            new_name='monthly_rate_limit',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='monthly_token_limit',
            field=models.IntegerField(default=0),
        ),
    ]
