# Generated by Django 3.2.18 on 2023-04-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230422_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='max_characters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('ultra', 'Ultra'), ('mega', 'Mega'), ('custom', 'Custom')], max_length=50),
        ),
    ]
