# Generated by Django 3.2.18 on 2023-04-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_instruction_instructioncategory_tone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='user_id',
        ),
    ]
