# Use the official Python base image with slim-buster
FROM python:3.8-slim

# Install system dependencies
RUN apt-get update && \
apt-get install -y gcc && \
apt-get install -y libpq-dev

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Upgrade pip
RUN pip install --upgrade pip

RUN ls

# # Create directory for the app
# WORKDIR /app

# # Copy project files
# COPY ./app /app

# # Copy entrypoint.dev.sh and make it executable
# COPY ./docker/dev/python/entrypoint.dev.sh /app/entrypoint.dev.sh
# RUN chmod +x /app/entrypoint.dev.sh

# # Install Python dependencies
# COPY ./app/requirements /app/requirements

# # Output pip installation log to console
# RUN pip install --no-cache-dir -r /app/requirements/dev.txt

# # Run entrypoint.dev.sh
# ENTRYPOINT ["/app/entrypoint.dev.sh"]
