FROM python:3.9-slim-buster

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create directory for the app user
WORKDIR /app

# Copy project files
COPY ./app /app

# Copy entrypoint.dev.sh and make it executable
COPY ./docker/dev/python/entrypoint.dev.sh /app/entrypoint.dev.sh
RUN chmod +x /app/entrypoint.dev.sh

RUN apt-get update && apt-get install -y netcat

# Copy requirements and install dependencies
COPY ./app/requirements /app/requirements

# Run entrypoint.dev.sh
ENTRYPOINT ["/app/entrypoint.dev.sh"]
